class SubItems {
final Map<String, List<String>> _subItems = {
  "Manage": [
    "Banks and Accounts",
    "Products",
    "Services",
    "All Contacts",
    "Customers",
    "Suppliers",
    "Agents",
    "Employees",
    "Employees Access",
    "Expense Types",
    "Locations/Warehouse",
    "Manufacturing Jobs",
  ],
  "Transaction": [
    "Sale Invoice",
    "WholeSale Invoice",
    "Sales Return",
    "Purchase Invoice",
    "Purchase Return",
    "New Expense",
    "New Payments",
    "Stock Transfer",
    "Manufacturing Jobs",
    "Journal Entry",
  ],
  "Reports": [
    "General Journal",
    "Stock Report",
    "Lended Inventory",
    "Purchase Rate List",
    "Sale Rate List",
    "Sold Items",
    "Profit and Loss",
    "Balance Sheet",
    "Receivable / Payable",
    "Daily Report",
    "Purchase Report by Supplier",
    "Sales Report by Customer",
    "Sales Report",
    "Cash Sales",
    "Credit Sales",
    "Partially Paid Sales",
  ],
  "History": [
    "Sales History",
    "Sales Return History",
    "Sales Quotation History",
    "Purchases History",
    "Purchases Return History",
    "Expense History",
    "Payment History",
    "Stock Transfer",
  ],
  "Utilities": [
    "ToDo List",
    "Print Shipping",
    "Shipping History",
  ],
  "Setting": [
    "Profile",
    "Change Password",
    "Membership",
    "Buy Now",
    "Logout",
  ],
};
}